version: 2
updates:
  # CLI npm dependencies
  - package-ecosystem: "npm"
    directory: "/cli"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "cli"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    assignees:
      - "chsword"

  # GUI npm dependencies
  - package-ecosystem: "npm"
    directory: "/gui"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "gui"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    assignees:
      - "chsword"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci/cd"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    assignees:
      - "chsword"
